import { StyleSheet } from 'react-native';
import { COLOR_SCHEMES } from '../../constants/colors';

const createStyles = (palette) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: palette.background,
    },
    scroll: {
      flex: 1,
    },
    container: {
      width: '100%',
      maxWidth: 1200,
      alignSelf: 'center',
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 48,
      gap: 16,
    },
    heroCard: {
      backgroundColor: palette.card,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: palette.border,
      padding: 20,
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 24,
      elevation: 6,
      gap: 16,
    },
    heroTopRow: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      flexWrap: 'wrap',
    },
    backButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroEyebrow: {
      color: palette.primary,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      textAlign: 'right',
    },
    heroTitle: {
      color: palette.text,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '800',
      textAlign: 'right',
    },
    heroDescription: {
      color: palette.subText,
      fontSize: 15,
      lineHeight: 22,
      maxWidth: 720,
      textAlign: 'right',
    },
    heroActionRow: {
      flexDirection: 'row-reverse',
      gap: 10,
      flexWrap: 'wrap',
      alignItems: 'center',
    },
    secondaryButton: {
      minHeight: 44,
      paddingHorizontal: 16,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.background,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row-reverse',
      gap: 8,
    },
    secondaryButtonPressed: {
      opacity: 0.88,
    },
    secondaryButtonText: {
      color: palette.text,
      fontWeight: '600',
      fontSize: 14,
      textAlign: 'right',
    },
    heroNote: {
      borderRadius: 18,
      padding: 14,
      backgroundColor: palette.background,
      borderWidth: 1,
      borderColor: palette.border,
    },
    heroNoteText: {
      color: palette.subText,
      fontSize: 13,
      lineHeight: 19,
      textAlign: 'right',
    },
    statsRow: {
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      gap: 12,
    },
    statCard: {
      flexGrow: 1,
      minWidth: 140,
      borderRadius: 20,
      padding: 16,
      backgroundColor: palette.background,
      borderWidth: 1,
      borderColor: palette.border,
      gap: 6,
    },
    statLabel: {
      color: palette.subText,
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      textAlign: 'right',
    },
    statValue: {
      color: palette.text,
      fontSize: 28,
      fontWeight: '800',
      textAlign: 'right',
    },
    datasetTabs: {
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      gap: 10,
    },
    datasetTab: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
    },
    datasetTabActive: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    datasetTabText: {
      color: palette.subText,
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'right',
    },
    datasetTabTextActive: {
      color: palette.white,
    },
    workspaceCard: {
      backgroundColor: palette.card,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: palette.border,
      padding: 20,
      gap: 16,
    },
    workspaceHeader: {
      gap: 6,
    },
    workspaceTitle: {
      color: palette.text,
      fontSize: 22,
      fontWeight: '800',
      textAlign: 'right',
    },
    workspaceDescription: {
      color: palette.subText,
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'right',
    },
    toolbarRow: {
      flexDirection: 'row-reverse',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
      flexWrap: 'wrap',
    },
    toolbarInfo: {
      color: palette.subText,
      fontSize: 13,
      textAlign: 'right',
    },
    contentRow: {
      gap: 16,
    },
    contentRowWide: {
      flexDirection: 'row-reverse',
      alignItems: 'flex-start',
    },
    panel: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.background,
      padding: 16,
      gap: 14,
    },
    listPanel: {
      flex: 0.95,
      minWidth: 280,
    },
    editorPanel: {
      flex: 1.4,
      minWidth: 320,
    },
    panelHeader: {
      gap: 4,
    },
    panelTitle: {
      color: palette.text,
      fontSize: 18,
      fontWeight: '700',
      textAlign: 'right',
    },
    panelDescription: {
      color: palette.subText,
      fontSize: 13,
      lineHeight: 19,
      textAlign: 'right',
    },
    recordList: {
      gap: 10,
    },
    recordCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      padding: 14,
      gap: 6,
    },
    recordCardActive: {
      borderColor: palette.primary,
      backgroundColor: palette.primary + '10',
    },
    recordCardPressed: {
      opacity: 0.92,
    },
    recordTitle: {
      color: palette.text,
      fontSize: 15,
      fontWeight: '700',
      textAlign: 'right',
    },
    recordMeta: {
      color: palette.subText,
      fontSize: 13,
      lineHeight: 18,
      textAlign: 'right',
    },
    emptyState: {
      paddingVertical: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyStateText: {
      color: palette.subText,
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    statusCard: {
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
    },
    statusSuccess: {
      backgroundColor: palette.success + '12',
      borderColor: palette.success + '40',
    },
    statusError: {
      backgroundColor: palette.danger + '12',
      borderColor: palette.danger + '40',
    },
    statusText: {
      fontSize: 13,
      lineHeight: 19,
      textAlign: 'right',
    },
    statusTextSuccess: {
      color: palette.success,
    },
    statusTextError: {
      color: palette.danger,
    },
    fieldGroup: {
      gap: 8,
    },
    fieldLabel: {
      color: palette.text,
      fontSize: 14,
      fontWeight: '700',
      textAlign: 'right',
    },
    helperText: {
      color: palette.subText,
      fontSize: 12,
      lineHeight: 18,
      textAlign: 'right',
    },
    uploadCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      padding: 12,
      gap: 12,
    },
    uploadPreview: {
      width: '100%',
      height: 180,
      borderRadius: 14,
      backgroundColor: palette.background,
    },
    uploadPlaceholder: {
      width: '100%',
      minHeight: 180,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      borderStyle: 'dashed',
      backgroundColor: palette.background,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      padding: 16,
    },
    uploadPlaceholderCompact: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      borderStyle: 'dashed',
      backgroundColor: palette.background,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      minHeight: 80,
    },
    uploadPlaceholderText: {
      color: palette.subText,
      fontSize: 13,
      lineHeight: 19,
      textAlign: 'center',
    },
    uploadActions: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      flexWrap: 'wrap',
    },
    uploadCountText: {
      color: palette.subText,
      fontSize: 13,
      textAlign: 'right',
    },
    uploadGrid: {
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      gap: 10,
    },
    uploadGridItem: {
      position: 'relative',
      width: 88,
      height: 88,
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: palette.background,
    },
    uploadGridPreview: {
      width: '100%',
      height: '100%',
    },
    uploadRemoveBadge: {
      position: 'absolute',
      top: 6,
      left: 6,
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: 'rgba(0,0,0,0.7)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    inlineDangerButton: {
      minHeight: 44,
      paddingHorizontal: 14,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.danger + '55',
      backgroundColor: palette.danger + '12',
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row-reverse',
      gap: 8,
    },
    inlineDangerButtonText: {
      color: palette.danger,
      fontWeight: '700',
      fontSize: 13,
    },
    input: {
      minHeight: 48,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: palette.text,
      fontSize: 15,
      textAlign: 'right',
    },
    inputMultiline: {
      minHeight: 104,
      textAlignVertical: 'top',
    },
    inputReadOnly: {
      opacity: 0.72,
      backgroundColor: palette.background,
    },
    choiceRow: {
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      gap: 10,
    },
    choiceCustomInput: {
      marginTop: 10,
    },
    choiceChip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
    },
    choiceChipActive: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    choiceChipText: {
      color: palette.subText,
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
    },
    choiceChipTextActive: {
      color: palette.white,
    },
    pickerTrigger: {
      minHeight: 48,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    pickerValue: {
      flex: 1,
      color: palette.text,
      fontSize: 15,
      textAlign: 'right',
      marginLeft: 12,
    },
    pickerPlaceholder: {
      color: palette.subText,
    },
    pickerMenu: {
      marginTop: 8,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      overflow: 'hidden',
    },
    pickerOption: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    pickerOptionActive: {
      backgroundColor: palette.light.secondary,
    },
    pickerOptionText: {
      color: palette.text,
      fontSize: 14,
      textAlign: 'right',
      fontWeight: '600',
    },
    pickerOptionTextActive: {
      color: palette.primary,
    },
    toggleRow: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
    },
    toggleLabelBlock: {
      flex: 1,
      paddingLeft: 12,
      gap: 4,
    },
    toggleTitle: {
      color: palette.text,
      fontSize: 14,
      fontWeight: '700',
      textAlign: 'right',
    },
    toggleDescription: {
      color: palette.subText,
      fontSize: 12,
      lineHeight: 18,
      textAlign: 'right',
    },
    toggleTrack: {
      width: 54,
      height: 30,
      borderRadius: 999,
      paddingHorizontal: 3,
      justifyContent: 'center',
      backgroundColor: palette.border,
    },
    toggleTrackActive: {
      backgroundColor: palette.primary,
    },
    toggleThumb: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: palette.white,
    },
    toggleThumbActive: {
      alignSelf: 'flex-end',
    },
    actionsRow: {
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      gap: 10,
      marginTop: 8,
    },
    dangerButton: {
      minHeight: 48,
      paddingHorizontal: 18,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.danger + '55',
      backgroundColor: palette.danger + '12',
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row-reverse',
      gap: 8,
    },
    dangerButtonText: {
      color: palette.danger,
      fontWeight: '700',
      fontSize: 14,
    },
    growButton: {
      flexGrow: 1,
    },
  });

export default {
  light: createStyles(COLOR_SCHEMES.light),
  dark: createStyles(COLOR_SCHEMES.dark),
};
